---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkinspvstore
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-storage
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkinspvstore
  hostPath:
    path: /mnt/data/jenkins
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-storage
spec:
  storageClassName: jenkinspvstore
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
