apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      # Add an init container to fix permissions
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home && chmod -R 775 /var/jenkins_home"]
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50000
              name: agent
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc-storage
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: agent
  type: NodePort

---
# Jenkins Service
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http #kubectl port-forward service/jenkins-master 8080:8080 -n jenkins
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: agent
  type: LoadBalancer
